### ISSUE TITLE
build error on filters, perhaps just gcc 4.4 (?)  (ros ticket #2734)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_common#141]
not sure if this is just gcc 4.4, but anyway the trunk of the common stack, filters package, doesn't build on my box (gcc 4.4, arch linux 64-bit):

{{{
  [ 75%] Building CXX object CMakeFiles/median.dir/src/median.o
  In file included from /opt/ros/latest/stacks/common/filters/src/median.cpp:31:
  /opt/ros/latest/stacks/common/filters/include/filters/filter_base.h: In member function ‘bool filters::MultiChannelMedianFilter<T>::update(const std::vector<T, std::allocator<_CharT> >&, std::vector<T, std::allocator<_CharT> >&) [with T = double]’:
  /opt/ros/latest/stacks/common/filters/src/median.cpp:41:   instantiated from here
  /opt/ros/latest/stacks/common/filters/include/filters/filter_base.h:283: error: ‘bool filters::FilterBase<double>::configured_’ is protected
  /opt/ros/latest/stacks/common/filters/include/filters/median.h:247: error: within this context
}}}

trac data:
- Owner: **tfoote**
- Reporter: **mquigley**
- Reported at: **Thu Sep  3 09:29:15 2009**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/2734

**Comment by ahendrix** [comment]
[tfoote] filters/include/filters/median.h:247
{{{
  if (!this->configured_)
}}}

Does gcc 4.4 now enforce that you must cast a pointer to it's base class to use a base method?  Or does it not like the fact that this call is using a pointer instead of just referencing itself?  

I would have expected 
{{{
if (!configured_)
}}}
to work but it doesn't.
{{{
/home/tfoote/ros/ros-pkg/stacks/common/filters/include/filters/median.h:247: error: ‘configured_’ was not declared in this scope
}}}
So I added the "this->" to make it find the symbol.

**Comment by ahendrix** [comment]
[tfoote] Morgan, can you try this patch?  I don't have arch available to me.

{{{

# === include/filters/median.h

--- include/filters/median.h    (revision 33880)
+++ include/filters/median.h    (local)
@@ -120,7 +120,7 @@

##    uint32_t number_of_observations_;             ///< Number of observations over which to filter
-  using FilterBase<T>::configured_;
  };
  
  template <typename T>
  @@ -156,7 +156,7 @@
  template <typename T>
  bool MedianFilter<T>::update(const T& data_in, T& data_out)
  {
-  if (!this->configured_)
-  if (!configured_)
   return false;
  
  data_storage_->push_back(data_in);
  @@ -204,7 +204,7 @@
  
  ## uint32_t number_of_observations_;             ///< Number of observations over which to filter
-  using FilterBase<T>::configured_;
  };
  
  template <typename T>
  @@ -244,7 +244,7 @@
  //  printf("Expecting width %d, got %d and %d\n", width_, data_in.size(),data_out.size());
  if (data_in.size() != this->number_of_channels_ || data_out.size() != this->number_of_channels_)
   return false;
-  if (!this->configured_)
-  if (!configured_)
   return false;
  
  data_storage_->push_back(data_in);
  }}}

**Comment by ahendrix** [comment]
[mquigley] looks like it's still unhappy:

{{{
  [ 75%] Building CXX object CMakeFiles/median.dir/src/median.o
  In file included from /home/mquigley/ros/ros-pkg/stacks/common/filters/src/median.cpp:31:
  /home/mquigley/ros/ros-pkg/stacks/common/filters/include/filters/median.h: In instantiation of ‘filters::MultiChannelMedianFilter<float>’:
  /home/mquigley/ros/ros-pkg/stacks/common/pluginlib/include/Poco/MetaObject.h:165:   instantiated from ‘B\* Poco::MetaObject<C, B>::create() const [with C = filters::MultiChannelMedianFilter<float>, B = filters::MultiChannelFilterBase<float>]’
  /home/mquigley/ros/ros-pkg/stacks/common/filters/src/median.cpp:41:   instantiated from here
  /home/mquigley/ros/ros-pkg/stacks/common/filters/include/filters/filter_base.h:283: error: ‘bool filters::FilterBase<float>::configured_’ is protected
  /home/mquigley/ros/ros-pkg/stacks/common/filters/include/filters/median.h:183: error: within this context
  /home/mquigley/ros/ros-pkg/stacks/common/filters/include/filters/median.h: In instantiation of ‘filters::MultiChannelMedianFilter<double>’:
  /home/mquigley/ros/ros-pkg/stacks/common/pluginlib/include/Poco/MetaObject.h:165:   instantiated from ‘B\* Poco::MetaObject<C, B>::create() const [with C = filters::MultiChannelMedianFilter<double>, B = filters::MultiChannelFilterBase<double>]’
  /home/mquigley/ros/ros-pkg/stacks/common/filters/src/median.cpp:41:   instantiated from here
  /home/mquigley/ros/ros-pkg/stacks/common/filters/include/filters/filter_base.h:283: error: ‘bool filters::FilterBase<double>::configured_’ is protected
  /home/mquigley/ros/ros-pkg/stacks/common/filters/include/filters/median.h:183: error: within this context
  make[3]: **\* [CMakeFiles/median.dir/src/median.o] Error 1
}}}

**Comment by ahendrix** [comment]
[mquigley] this is pretty hardcore c++. maybe it needs a "friend" declaration somewhere to expose the protected member to a template instantiation?

**Comment by ahendrix** [comment]
[tfoote] it's inheriting a templated base class, two layers deep.  I don't understand why the protected variables are available to the derived class.  

Josh, could you take a look?

**Comment by ahendrix** [comment]
[jfaust] http://www.parashift.com/c++-faq-lite/templates.html#faq-35.19

If this->configured_ doesn't work (though it looks like it should), try FilterBase<T>::configured_.  The using statement will also work.

It does look like you fixed the MedianFilter, it's the MultiChannelMedianFilter that's still having problems according to Morgan's last error message.

**Comment by ahendrix** [comment]
[mquigley] I think the original error was in MultiChannelMedianFilter. The odd thing is that it doesn't seem to be an error in name lookup, but rather in visiblity: it knows that we're referring to FilterBase<T>::configured_  and it's convinced that we can't access it because it's protected. Is this a consequence of not defining the template functions inside the template class declaration?

And for a more heretical question, is the uber-template approach really required or needed in this case?

**Comment by ahendrix** [comment]
[tfoote] so I tried calling FilterBase<T>::configured_ explicitly.  committed as r23836

**Comment by ahendrix** [comment]
[tfoote] in ros-pkg
